const moment = require('moment');

module.exports = { 
    "TIMEZONE" : "Asia/Kolkata",
    "SUCCESS" : "SUCCESS",
    "ERROR" : "ERROR",
    "BAD_DATA" : "BAD_DATA",
    "BACKEND_API_FAILURE" : "BACKEND_API_FAILURE",
    "CODE"  : "CODE",
    "ERROR_CODE" : 400,
    "APPROVED" : "APPROVED",
    "INVALID_REQUEST" : "INVALID_REQUEST",
    "CURRENT_DATE" : moment().format('YYYY-MM-DD hh:mm:ss'),
    "LAST_UPDATE" : 'YYYY-MM-DD hh:mm:ss',
    "HASH_STRING_LIMIT" : 12,
    "SUCCESS_CODE" : 200,
    "USERROLE": 1,
    "APPURL" : "",
    "JWT_EXPIRE_LIMIT" : 1,
    "REGISTER" : "/register",
    "LOGIN" : "/login",
    "FORGOTPASSWORD" : "/forgot-password",
    "RESETPASSWORD" : "/reset-password",
    "CHANGEPASSWORD" : "/change-password",
    "GETPROFILE" : "/get-profile",
    "UPDATEPROFILE" : "/update-profile",
    "VERIFYTOKEN" : "/change-tokenStatus",
    "ADDMEDIA" : "/add-media",
    "IMAGEPATH" : "",
    'GETMEDIA' : "/get-media",
    "ADDGAME" : "/add-game",
    "ADDQUESTION" : "/add-question",
    "GETQUESTION" : "/get-question",
    "JOINGAME" : "/join-game",
    "LOBBYDETAIL" : "/get-lobbydetails",
    "STARTGAME" : "/start-game",
    "FINISHPROJECT" : "/finish-project",
    "GETGAMEDETAIL" : "/game-detail",
    "UPDATEQUESTION" : "/update-question",
    "DELETEQUESTION" : "/delete-question",
    "GETALLGAMES" : "/get-gameDetail",
    "UPDATEGAME" : "/update-game",
    "DELETEGAME" : "/delete-game",
    "GETGAMEBYID" : "/get-gameDetailByID",
    "GETQUESTIONBYGAMEID" : "/get-questionByGameId",
    "SAVE_QUE_ANS" : "/save-question-answer",
    "CREATEDUPLICATE" : "/create-duplicate",
    "GETGAMESTUDENT" : "/get-game-student",
    "GETGAMERESULT" : "/get-game-result",
    "GETGAMESTATUS" : "/get-game-status",
    "ADDWINPOINT" : "/add-winPoint",
    "GETSAVEQUEANS" : "/get-save-quesAns",
    "UPDATESAVEQUQANS" : "/update-save-queAns",
    "GETRESULT" : "/get-result",
    "ADMINLOGIN" : "/admin-login",
    "FINISHGAME" : "/finish-game",
    "COUNTDETAILS" : "/get-detail",
    "GAMEDATA" : "/get-game-data",
    "TOTALGAMEMEMBER" : "/total-game-member",
    "GETSTUDENTRESULT" : "/get-student-result",
    
}